# Generated by Django 5.2.5 on 2025-08-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espaciocurricular",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="espacios",
                to="academia_core.planestudios",
            ),
        ),
    ]
