# Generated by Django 5.2.5 on 2025-08-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0002_add_plan_to_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espaciocurricular",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="espacios",
                to="academia_core.planestudios",
            ),
        ),
    ]
