# Generated by Django 5.2.5 on 2025-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0004_auto_20250824_2104"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorePerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "open_close_windows",
                        "Puede abrir/cerrar ventanas de inscripción",
                    ),
                    ("enroll_self", "Puede inscribirse a sí mismo"),
                    ("enroll_others", "Puede inscribir a terceros"),
                    ("manage_correlatives", "Puede gestionar correlatividades"),
                    ("publish_grades", "Puede publicar calificaciones"),
                    (
                        "view_any_student_record",
                        "Puede ver ficha/cartón de cualquier estudiante",
                    ),
                    ("edit_student_record", "Puede editar ficha/cartón de estudiantes"),
                    ("view_inscripcioncarrera", "Puede ver inscripciones a carrera"),
                    ("add_inscripcioncarrera", "Puede crear inscripciones a carrera"),
                    (
                        "change_inscripcioncarrera",
                        "Puede editar inscripciones a carrera",
                    ),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
