# Generated by Django 5.2.5 on 2025-08-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0005_coreperms"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitosIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_dni", models.BooleanField(default=False)),
                ("req_cert_med", models.BooleanField(default=False)),
                ("req_fotos", models.BooleanField(default=False)),
                ("req_folios", models.BooleanField(default=False)),
                ("req_titulo_sec", models.BooleanField(default=False)),
                ("req_titulo_tramite", models.BooleanField(default=False)),
                ("req_adeuda", models.BooleanField(default=False)),
                ("req_adeuda_mats", models.CharField(blank=True, max_length=255)),
                ("req_adeuda_inst", models.CharField(blank=True, max_length=255)),
                ("req_titulo_sup", models.BooleanField(default=False)),
                ("req_incumbencias", models.BooleanField(default=False)),
                ("req_condicion", models.BooleanField(default=False)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos",
                        to="academia_core.estudianteprofesorado",
                    ),
                ),
            ],
        ),
    ]
