# Generated by Django 5.2.5 on 2025-08-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0006_requisitosingreso"),
        ("academia_core", "0007_repair_coreperms_table"),
    ]

    operations = []
