# Generated by Django 5.2.5 on 2025-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0009_carrera_inscripcioncarrera_materia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
            },
        ),
    ]
