# Generated by Django 5.2.5 on 2025-09-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0010_aula"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Horario",
        ),
    ]
