# Generated by Django 5.2.5 on 2025-08-31 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academia_core", "0008_merge_20250831_0510"),
    ]

    operations = [
        migrations.CreateModel(
            name="MateriaEnPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                (
                    "tipo_dictado",
                    models.CharField(
                        choices=[
                            ("ANUAL", "Anual"),
                            ("CUATRIMESTRAL", "Cuatrimestral"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "horas_catedra_semana_1c",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "horas_catedra_semana_2c",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "horas_catedra",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Cantidad semanal de horas cátedra (40’). Dejar vacío = sin tope.",
                        null=True,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_core.espaciocurricular",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_core.planestudios",
                    ),
                ),
            ],
            options={
                "db_table": "academia_horarios_materiaenplan",
                "unique_together": {("plan", "materia", "anio")},
            },
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ciclo_lectivo", models.PositiveIntegerField()),
                (
                    "cuatrimestre",
                    models.PositiveSmallIntegerField(choices=[(1, "1°"), (2, "2°")]),
                ),
            ],
            options={
                "db_table": "academia_horarios_periodo",
                "unique_together": {("ciclo_lectivo", "cuatrimestre")},
            },
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manana", "Mañana"),
                            ("tarde", "Tarde"),
                            ("vespertino", "Vespertino"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("nombre", models.CharField(default="Única", max_length=16)),
                ("cupo", models.PositiveSmallIntegerField(default=0)),
                (
                    "materia_en_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_horarios.materiaenplan",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_horarios.periodo",
                    ),
                ),
            ],
            options={
                "db_table": "academia_horarios_comision",
                "unique_together": {("materia_en_plan", "periodo", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_semana", models.PositiveSmallIntegerField()),
                ("inicio", models.TimeField()),
                ("fin", models.TimeField()),
            ],
            options={
                "db_table": "academia_horarios_timeslot",
                "indexes": [
                    models.Index(
                        fields=["dia_semana", "inicio", "fin"],
                        name="academia_ho_dia_sem_cb4c98_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inicio__lt", models.F("fin"))),
                        name="timeslot_inicio_lt_fin",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HorarioClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aula", models.CharField(blank=True, default="", max_length=64)),
                ("observaciones", models.TextField(blank=True, default="")),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="academia_horarios.comision",
                    ),
                ),
                (
                    "docentes",
                    models.ManyToManyField(blank=True, to="academia_core.docente"),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_horarios.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "academia_horarios_horarioclase",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comision", "timeslot"),
                        name="uniq_horario_por_comision_bloque",
                    )
                ],
            },
        ),
    ]
