# Generated by Django 5.2.5 on 2025-08-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0002_horario"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comision",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comision",
            name="seccion",
            field=models.CharField(default="A", max_length=2),
        ),
        migrations.AddField(
            model_name="horario",
            name="seccion",
            field=models.CharField(default="A", max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name="comision",
            unique_together={("materia_en_plan", "periodo", "seccion")},
        ),
    ]
