# Generated by Django 5.2.5 on 2025-09-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_core", "0010_aula"),
        (
            "academia_horarios",
            "0003_alter_comision_unique_together_comision_seccion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lun"),
                            (1, "Mar"),
                            (2, "Mié"),
                            (3, "Jue"),
                            (4, "Vie"),
                            (5, "Sáb"),
                        ]
                    ),
                ),
                ("orden", models.IntegerField()),
                ("inicio", models.TimeField()),
                ("fin", models.TimeField()),
                ("es_recreo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TurnoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Catedra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horas_semanales", models.PositiveSmallIntegerField()),
                ("permite_solape_interno", models.BooleanField(default=False)),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academia_horarios.comision",
                    ),
                ),
                (
                    "materia_en_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academia_horarios.materiaenplan",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_horarios.turnomodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocenteAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[("INTERINO", "Interino"), ("SUPLENTE", "Suplente")],
                        max_length=10,
                    ),
                ),
                ("fecha_desde", models.DateField()),
                ("fecha_hasta", models.DateField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "catedra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="academia_horarios.catedra",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academia_core.docente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocenteCobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coberturas",
                        to="academia_horarios.docenteasignacion",
                    ),
                ),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academia_horarios.bloque",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloque",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="academia_horarios.turnomodel",
            ),
        ),
        migrations.CreateModel(
            name="CatedraHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academia_horarios.bloque",
                    ),
                ),
                (
                    "catedra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to="academia_horarios.catedra",
                    ),
                ),
            ],
            options={
                "unique_together": {("catedra", "bloque")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bloque",
            unique_together={("turno", "dia_semana", "orden")},
        ),
    ]
