# Generated by Django 5.2.5 on 2025-09-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia_core', '0010_aula'), # Last migration from academia_core
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_lectivo', models.PositiveIntegerField()),
                ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°')])),
            ],
            options={
                'db_table': 'academia_horarios_periodo',
                'unique_together': {('ciclo_lectivo', 'cuatrimestre')},
            },
        ),
        migrations.CreateModel(
            name='TurnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
            ],
            options={
                'db_table': 'academia_horarios_timeslot',
                'indexes': [models.Index(fields=['dia_semana', 'inicio', 'fin'], name='academia_ho_dia_se_12345')],
                'constraints': [models.CheckConstraint(check=models.Q(inicio__lt=models.F('fin')), name='timeslot_inicio_lt_fin')],
            },
        ),
        migrations.CreateModel(
            name='MateriaEnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('tipo_dictado', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=16)),
                ('horas_catedra_semana_1c', models.PositiveSmallIntegerField(default=0)),
                ('horas_catedra_semana_2c', models.PositiveSmallIntegerField(default=0)),
                ('horas_catedra', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad semanal de horas cátedra (40’). Dejar vacío = sin tope.', null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_core.espaciocurricular')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_core.planestudios')),
            ],
            options={
                'db_table': 'academia_horarios_materiaenplan',
                'unique_together': {('plan', 'materia', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('vespertino', 'Vespertino'), ('sabado', 'Sábado')], max_length=16)),
                ('nombre', models.CharField(default='Única', max_length=16)),
                ('cupo', models.PositiveSmallIntegerField(default=0)),
                ('seccion', models.CharField(default='A', max_length=2)),
                ('materia_en_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.materiaenplan')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.periodo')),
            ],
            options={
                'db_table': 'academia_horarios_comision',
                'unique_together': {('materia_en_plan', 'periodo', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comision', models.CharField(blank=True, max_length=8)),
                ('aula', models.CharField(blank=True, max_length=64)),
                ('dia', models.CharField(choices=[('lu', 'Lunes'), ('ma', 'Martes'), ('mi', 'Miércoles'), ('ju', 'Jueves'), ('vi', 'Viernes'), ('sa', 'Sábado')], max_length=2)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('turno', models.CharField(blank=True, max_length=16)),
                ('cuatrimestral', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia_core.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_core.espaciocurricular')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_core.planestudios')),
                ('profesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_core.profesorado')),
            ],
            options={
                'db_table': 'academia_horarios_horario',
                'ordering': ('dia', 'inicio'),
                'indexes': [models.Index(fields=['materia', 'dia', 'inicio'], name='academia_ho_materia_d_12345')],
            },
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(blank=True, default='', max_length=64)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academia_horarios.comision')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.timeslot')),
                ('docentes', models.ManyToManyField(blank=True, to='academia_core.docente')),
            ],
            options={
                'db_table': 'academia_horarios_horarioclase',
                'constraints': [models.UniqueConstraint(fields=['comision', 'timeslot'], name='uniq_horario_por_comision_bloque')],
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lun'), (1, 'Mar'), (2, 'Mié'), (3, 'Jue'), (4, 'Vie'), (5, 'Sáb')])),
                ('orden', models.IntegerField()),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('es_recreo', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_horarios.turnomodel')),
            ],
            options={
                'unique_together': {('turno', 'dia_semana', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.PositiveSmallIntegerField()),
                ('permite_solape_interno', models.BooleanField(default=False)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_horarios.comision')),
                ('materia_en_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_horarios.materiaenplan')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.turnomodel')),
            ],
        ),
        migrations.CreateModel(
            name='CatedraHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_horarios.bloque')),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='academia_horarios.catedra')),
            ],
            options={
                'unique_together': {('catedra', 'bloque')},
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('INTERINO', 'Interino'), ('SUPLENTE', 'Suplente')], max_length=10)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academia_horarios.catedra')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_core.docente')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='academia_horarios.docenteasignacion')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia_horarios.bloque')),
            ],
        ),
    ]