# Generated by Django 5.0.7 on 2025-09-02 19:23

from django.db import migrations


TURNOS = [
    {"nombre": "Mañana", "slug": "manana"},
    {"nombre": "Tarde", "slug": "tarde"},
    {"nombre": "Vespertino", "slug": "vespertino"},
]

def populate_turnos(apps, schema_editor):
    TurnoModel = apps.get_model('academia_horarios', 'TurnoModel')
    for data in TURNOS:
        TurnoModel.objects.get_or_create(slug=data['slug'], defaults=data)

def reverse_populate_turnos(apps, schema_editor):
    TurnoModel = apps.get_model('academia_horarios', 'TurnoModel')
    slugs = [t['slug'] for t in TURNOS]
    TurnoModel.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academia_horarios', '0007_initial_rebuild'),
    ]

    operations = [
        migrations.RunPython(populate_turnos, reverse_code=reverse_populate_turnos),
    ]