# Generated by Django 5.2.5 on 2025-09-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0008_auto_20250902_1623"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="horario",
            new_name="academia_ho_materia_4c2a3e_idx",
            old_name="academia_ho_materia_d_12345",
        ),
        migrations.RenameIndex(
            model_name="timeslot",
            new_name="academia_ho_dia_sem_cb4c98_idx",
            old_name="academia_ho_dia_se_12345",
        ),
        migrations.AlterField(
            model_name="bloque",
            name="turno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academia_horarios.turnomodel",
            ),
        ),
    ]
