# Generated by Django 5.2.5 on 2025-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0010_auto_20250902_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="turno",
            field=models.CharField(
                choices=[
                    ("manana", "Mañana"),
                    ("tarde", "Tarde"),
                    ("vespertino", "Vespertino"),
                    ("sabado", "Sábado"),
                ],
                default="manana",
                max_length=16,
            ),
        ),
    ]
