name: CI (Lint, Check & Tests)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    permissions:
      contents: read
      actions: read

    env:
      DJANGO_SETTINGS_MODULE: academia_project.settings
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      USE_SQLITE_FOR_TESTS: "1"
      DJANGO_DEBUG: "1"
      TIME_ZONE: "UTC"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,testserver"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Sync deps
        run: |
          uv venv
          uv sync --locked || uv sync
          uv add --dev pytest pytest-django pytest-cov ruff tzdata

      - name: Ruff (non-blocking)
        run: uv run ruff check . || true

      - name: Django check
        run: uv run python manage.py check

      - name: Pytest + Coverage (XML + term)
        run: uv run pytest --cov --cov-report=xml --cov-report=term-missing -q

      - name: Enforce minimum coverage
        run: uv run coverage report --fail-under=${{ vars.COVERAGE_MIN || 0 }}

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml